import "./globals.css";
import { inter, vazirmatn } from "@/fonts.js";
import "@rainbow-me/rainbowkit/styles.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Providers } from "./provider";
import { ConnectButton } from "@rainbow-me/rainbowkit";
export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazirmatn.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
